### ISSUE TITLE
Failed saving images on konachan.com

### ISSUE THREAD

**Issue by eiurur** [eiurur/Save-to-Kawpaa#15]
{ content: null,
      title: 'aqua (konosuba) blue eyes blue hair bow breasts censored kono subarashii sekai ni shukufuku wo! nipples nude paizuri penis tagme (artist) | konachan.com - Konachan.com Anime Wallpapers',
      siteName: '',
      siteUrl: 'https://konachan.com/post/show/256865/aqua_-konosuba-blue_eyes-blue_hair-bow-breasts-cen',
      type: 'image',
      url: 'https:https://konachan.com/jpeg/7e3353bb362d47cea7f2ecb3fa0e2d16/Konachan.com%20-%20256865%20aqua_%28konosuba%29%20blue_eyes%20blue_hair%20bow%20breasts%20censored%20kono_subarashii_sekai_ni_shukufuku_wo%21%20nipples%20nude%20paizuri%20penis%20tagme_%28artist%29.jpg',
      hostName: 'konachan.com',
      description: 'Konachan.com - Image board site for Anime / Manga wallpapers. Unlimited and unrestricted downloads.',
      siteImage: 'https://konachan.com/images/stubs/explicit.png',
      favicon: 'https://konachan.com/favicon.ico',
      isPrivate: true,
      isArchive: false,
      postedBy:
      {  }
    save   ====>
    Oops x_x, saving error
    Error: Error: Invalid URI "https:https://konachan.com/jpeg/7e3353bb362d47cea7f2ecb3fa0e2d16/Konachan.com%20_%20256865%20aqua_%28konosuba%29%20blue_eyes%20blue_hair%20bow%20breasts%20censored%20kono_subarashii_sekai_ni_shukufuku_wo%21%20nipples%20nude%20paizuri%20penis%20tagme_%28artist%29.jpg"
        at KawpaaImageManager.save (D:\workspace\Github\development_projects\kawpaa\build\lib\KawpaaImageManager.js:77:15)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
    RangeError: Invalid status code: undefined
        at ServerResponse.writeHead (_http_server.js:188:11)
        at ServerResponse.writeHead (D:\workspace\Github\development_projects\kawpaa\node_modules\on-headers\index.js:55:19)
        at ServerResponse.writeHead (D:\workspace\Github\development_projects\kawpaa\node_modules\on-headers\index.js:55:19)
        at ServerResponse.writeHead (D:\workspace\Github\development_projects\kawpaa\node_modules\on-headers\index.js:55:19)
        at ServerResponse._implicitHeader (_http_server.js:179:8)
        at ServerResponse.end (D:\workspace\Github\development_projects\kawpaa\node_modules\compression\index.js:103:14)
        at ServerResponse.send (D:\workspace\Github\development_projects\kawpaa\node_modules\express\lib\response.js:211:10)
        at ServerResponse.json (D:\workspace\Github\development_projects\kawpaa\node_modules\express\lib\response.js:256:15)
        at app.post (D:\workspace\Github\development_projects\kawpaa\build\app\routes\api\publics.js:63:43)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by eiurur** [comment]
## URL

https://konachan.com/post/show/256865/aqua_-konosuba-blue_eyes-blue_hair-bow-breasts-cen

## Result

![chrome_2018-04-06_01-03-48](https://user-images.githubusercontent.com/4101830/38377667-78acd718-3936-11e8-8f4c-d183e3d2fd01.png)

![chrome_2018-04-06_01-03-58](https://user-images.githubusercontent.com/4101830/38377672-7c98a474-3936-11e8-827e-e29cf0e07932.png)
