### ISSUE TITLE
Failed to save on beta.sankakucomplex.com

### ISSUE THREAD

**Issue by eiurur** [eiurur/Save-to-Kawpaa#45]
<a href="https://www.npmjs.com/package/open-graph" target="_blank">open-graph</a>のリクエストでエラーが発生している模様。

```
[2020-10-11T22:26:55.919] [ERROR] default - seq onError statusCode =>   undefined
[2020-10-11T22:26:55.920] [ERROR] default - seq onError message =>   Request failed with HTTP status code: 500
[2020-10-11T22:26:55.921] [ERROR] default - seq onError trace=>   Error: Request failed with HTTP status code: 500
    at Request._callback (D:\workspace\Github\development_projects\00_developing\kawpaa\node_modules\open-graph\index.js:51:8)
    at Request.self.callback (D:\workspace\Github\development_projects\00_developing\kawpaa\node_modules\request\request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.<anonymous> (D:\workspace\Github\development_projects\00_developing\kawpaa\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:311:20)
    at IncomingMessage.<anonymous> (D:\workspace\Github\development_projects\00_developing\kawpaa\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:417:28)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
POST /api/posts 500 598.752 ms - 43
```

**Comment by eiurur** [comment]
descriptionが空でtitleもサイト名しか載っていないので判読性は薄いが保存できるようになった。

![chrome_2020-10-11_22-56-10](https://user-images.githubusercontent.com/4101830/95680462-f852fe80-0c14-11eb-8f87-d26c4abe0f2e.png)

![chrome_2020-10-11_22-54-36](https://user-images.githubusercontent.com/4101830/95680463-fa1cc200-0c14-11eb-9ca0-360c9e673526.png)

**Comment by eiurur** [comment]
webshot-nodeからpuppeteerに置き換えたらSPAにも対応できた。

- https://beta.sankakucomplex.com/post/show/21615854?tags=order%3Apopularity%20bang_dream%21
- https://twitter.com/MP26player/status/1286817123596042240


![chrome_2020-10-12_00-09-22](https://user-images.githubusercontent.com/4101830/95682250-3ce39780-0c1f-11eb-9dcf-9d1a71c3f96f.png)
